feat: supports processHtml function
jd-opensource/micro-app pull request #434
Opened 2022-06-17 16:13 UTC by keuby

2022-06-20 13:13 UTC, dream2023 commented
建议增加上测试用例和文档。

如果没时间，我也可以一起做。

2022-06-20 13:33 UTC, dream2023 requested changes
- [x] 功能
- [ ] 文档
- [ ] 测试用例

2022-06-20 13:38 UTC, dream2023 approved these changes

2022-06-20 14:15 UTC, dream2023 commented
已给你的仓库提交了 PR

https://github.com/keuby/micro-app/pull/1

2022-06-21 01:43 UTC, dream2023 commented
@bailicangdu 大概说一下这个功能的背景。

目前的 plugin `loader` 只能修改 JS 文件，但是很多时候需要注入一些 script 或者 CSS 或者替换一些东西。

目前虽然能通过自定义 fetch，拿到内容然后修改，但毕竟这种方式不够优雅。

通过 html-process 这种方式，就可以很好的解决这个问题。

2022-06-21 02:51 UTC, bailicangdu commented
感谢PR，思路不错，但appInterface不能传递给processHtml，它是一个私域变量，不应该暴露给用户

2022-06-21 03:28 UTC, dream2023 commented
> 感谢PR，思路不错，但appInterface不能传递给processHtml，它是一个私域变量，不应该暴露给用户

@keuby 那就把 `appInterface` 删掉 😂

2022-06-21 04:24 UTC, keuby commented
> @keuby 那就把 appInterface 删掉 😂

🐶 那我去掉

2022-06-21 05:33 UTC, merged